name: cornerstoneclarkston
favicon: null
layout_spectrum: 0.36428135680034757
typography_spectrum: 0.9921640679240227
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6905985050834715
  lightness: 0.746499145636335
  saturation: 0.4133260997477919
  rhythmicContrast: 0.27156839868985116
purpose: []
